# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20160921_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Participant')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='relation',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Team'),
        ),
    ]
