# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20160922_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='team_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='team_id',
            field=models.ManyToManyField(to='portal.Team'),
        ),
    ]
