# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20160922_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='team_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Team'),
            preserve_default=False,
        ),
    ]
