# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20160922_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='team_id',
            new_name='team',
        ),
    ]
