# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20160928_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
